# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener: true
  format_listener:
    rules:
    - { path: ^/v1, priorities: [ 'json' ], fallback_format: json, prefer_extension: true }
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json: true